"use client";
import ClientLayout from "@/components/common/ClientLayout";
import AdminLayout from "@/components/admin/AdminLayout";
import {getFirstURISegment} from "@/utility/uriSegment.utility";
import {PrimeReactProvider} from "primereact/api";

export default function RootLayout({children}) {
    const url = getFirstURISegment() + "/admin";
    const isAdminPage = url && url.startsWith("van-tai-noi-dia/admin");

    return (

        <>
            {isAdminPage ?
                <><AdminLayout>{children}</AdminLayout></>
                :
                <html lang="vi">
                <head>
                    <meta charSet="UTF-8"/>
                    <title>Con Rùa Biển - Chành Xe đi Phú Quốc | 0945000006</title>
                    <meta name="description" content="Generated by Next.js"/>
                    <link rel="icon" href="#"/>
                    {/*<link rel="stylesheet" href="../assets/css/master.css" />*/}
                </head>
                <body>

                <div>
                    <ClientLayout>
                        <PrimeReactProvider>{children}</PrimeReactProvider>
                    </ClientLayout>
                </div>


                {/*/!*Main*!/*/}
                {/*<Script src="/js/jquery-1.11.3.min.js"></Script>*/}
                {/*<Script src="/js/jquery-ui.min.js"></Script>*/}
                {/*<Script src="/js/bootstrap.min.js"></Script>*/}
                {/*<Script src="/js/modernizr.custom.js"></Script>*/}

                {/*/!*<Script src="/rendro-easy-pie-chart/dist/jquery.easypiechart.min.js"></Script>*!/*/}
                {/*<Script src="/js/waypoints.min.js"></Script>*/}
                {/*<Script src="/js/jquery.easypiechart.min.js"></Script>*/}
                {/*/!*Owl Carousel*!/*/}
                {/*/!* <Script src="/owl-carousel/owl.carousel.min.js"></Script> *!/*/}
                {/*/!* SCRIPTS *!/*/}
                {/*<Script*/}
                {/*    type="text/javascript"*/}
                {/*    src="../../public/isotope/jquery.isotope.min.js"*/}
                {/*></Script>*/}
                {/*/!*Theme*!/*/}
                {/*/!*<Script src="/js/jquery.smooth-scroll.js"></Script>*!/*/}
                {/*<Script src="/js/wow.min.js"></Script>*/}
                {/*<Script src="/js/jquery.placeholder.min.js"></Script>*/}
                {/*/!*<Script src="/js/smoothscroll.min.js"></Script>*!/*/}
                {/*<Script src="/js/theme.js"></Script>*/}
                </body>
                </html>
            }
        </>
    );
}